name: Finn Car Parser

on:
  schedule:
    - cron: "0 */6 * * *"   # каждые 6 часов
  workflow_dispatch:        # можно запускать вручную

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run parser
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Save state files (seen_ads.json + ads_log.txt)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add seen_ads.json ads_log.txt || true
          git commit -m "update state files" || true
          git push
