name: Run Car Parser

on:
  workflow_dispatch:  # запуск вручную с GitHub
  schedule:
    - cron: "0 7,17 * * *"  # запуск каждый день в 07:00 и 17:00 (UTC)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python car_parser.py

      - name: Commit updated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add seen_ads.json ads_log.txt || true
          git commit -m "Update seen ads" || true
          git push
